### ISSUE TITLE
can't find or change the todo.txt in the mobile app

### ISSUE THREAD

**Issue by ClementBoesmier** [xuhcc/mindstream#1] opened 2020-02-13 17:19 UTC
when I go to setting and use browse button and go to my 'todo.txt' file the path champ is empty

I have a honor 8 by huawei in android 7 

sorry for my english i'm frensh

**Comment by xuhcc** [comment] 2020-02-13 17:46
Hello! What version you are using?

**Comment by xuhcc** [comment] 2020-02-16 21:05
I don't have this device, but I loaded Android 7.1.1 into the emulator, and didn't notice any issues with the settings page or file picker there.

I'll enable error messages in the next version to help debug similar cases.

**Comment by aisbergde** [comment] 2020-05-21 20:18
similair issue:
I can use browse and I can browse and select another todo.txt but nothing happens when I select the file, the file path used by the app doesn't change.
I use the latest available version.

**Comment by xuhcc** [comment] 2020-05-21 22:32
@aisbergde I was unable to reproduce it.

But the latest version of the app (1.3.0) should show error messages near the bottom of the screen if it fails to read the file. Are you seeing them? If so, can you take a screenshot and post it here?

**Comment by aisbergde** [comment] 2020-05-22 07:36
no error, only nothing happens.
If I select "browse" I can only choice between
- Dateien (Files)
- OPlayer
This is already a limited selection, because the buildin file selector could be the problem but I am not asked to use some other installed file managers

Now I can browse to the desired file and I have 2 possibilities:
- short tap the file
  - this will return to mindstream but nothing happens
- long tap to the file to select it and the "auswählen" (select)
  - this will return to mindstream but nothing happens

it looks like there is a missing step between selecting a file and using the selection. And no error message. It looks like mindstream forgets to use the content of the selection.

the automatically generated location is
`/data/user/0/im.mindstream.mobile/files/todo.txt`

Now I tried to write manually the file location like this (what the app forgets to do):
`/storage/emulated/0/Documents/markor/todo.txt`
and I click "save"
this finally generate an error that the app can't read the app.
>Error:ReadTextTask returns no result
or so, it is displayed only very short

now I will try some other path with a not existing document
`/data/user/0/Documents/markor/todo.txt`
But doing so the "save button" will not be activated

And my understanding is:
- the save button will be only activated if the file exist
- `/storage/emulated/0/Documents/markor/todo.txt` is a valid file location
- mindstream can't read this file

So we have 2 parts of the issue:
1. a file can't be selected
2. a file can't be read

**Comment by xuhcc** [comment] 2020-05-22 14:31
Thank you for your analysis

>the save button will be only activated if the file exist

That's true.

>/storage/emulated/0/Documents/markor/todo.txt is a valid file location
>mindstream can't read this file

I succeeded in reproducing this problem, but with another location. It turned out that file picker couldn't determine the file path when the file is being selected from "SD card" location. I fixed this bug, improved error handling and published a new version: https://github.com/xuhcc/mindstream/releases/tag/v1.3.1.

Let me know if it would work for you.

**Comment by aisbergde** [comment] 2020-05-23 13:20
now I get on startup and every minute (or so):

error java.io.IOException permission denied

I can pickup a file but it is shown as a not existing file - save button is disabled.

**Comment by aisbergde** [comment] 2020-05-23 13:24
and I can add tasks, but it is not clear which file is used. it is not the file I try to use in the settings, but maybe it is the default file.

**Comment by xuhcc** [comment] 2020-05-24 18:48
>now I get on startup and every minute (or so):
>error java.io.IOException permission denied

The app re-loads the file every minute, so I guess these are filesystem read errors. Maybe it's a permission issue (the app should have asked for them on the first start).

>and I can add tasks, but it is not clear which file is used. it is not the file I try to use in the settings, but maybe it is the default file.

Tasks remain in memory when added (so you can see them in the list), but it seems that the app can't write to the file you selected. The file used is always the one selected in settings.

**Comment by aisbergde** [comment] 2020-05-24 21:53
I granted all rights I was asked. and there is only one right.
btw: today I get a different error. Not the error with ioPermission, today I can select a different file and I can press "save" 
but then I get the old error - can't read result - nearly every minute 
version is v1. 3.1

**Comment by xuhcc** [comment] 2020-05-24 22:46
What version of Android your phone is running?

**Comment by aisbergde** [comment] 2020-05-25 06:43
Android 10 QKQ1.190828.002
MIUI global 11.0.8 (stable)

If you emulate this in Android 7 then there could be changes in the permission system since Android 7

btw, I would need a todo.txt app which allow me to easy switch between different files like todo, waiting, someday
And I am looking for easy ways to move entries between these files. For example 
- assign some tasks the tag "waiting"
- using the filter (you have this already)
- move selected files into another file

could you imagine to implement this? было бы хорошо.

**Comment by xuhcc** [comment] 2020-05-25 11:47
>If you emulate this in Android 7 then there could be changes in the permission system since Android 7

Yes, that was the case. I found the problem and fixed it in version 1.3.2.

> btw, I would need a todo.txt app which allow me to easy switch between different files like todo, waiting, someday
> And I am looking for easy ways to move entries between these files. For example
> 
>     assign some tasks the tag "waiting"
>     using the filter (you have this already)
>     move selected files into another file
> 
> could you imagine to implement this? было бы хорошо.

Mindstream was designed to work with single-file todos, so this is unlikely to be implemented. I keep all my current tasks in a single file and categorize them with tags, priorities and due dates. Once in a while I move all completed tasks to `done.txt` using the todo.txt CLI (on desktop).

**Comment by aisbergde** [comment] 2020-05-25 11:57
I will check the new version if it will be in Google Play Store.

> Mindstream was designed to work with single-file todos, so this is unlikely to be implemented. I keep all my current tasks in a single file and categorize them with tags, priorities and due dates. Once in a while I move all completed tasks to `done.txt` using the todo.txt CLI (on desktop).

it looks like this is the main way how a lot of people are using the system. My idea was to distinguish between private tasks and customer project related tasks and to keep the current file small and clean. Maybe I will consider to test the usage of one big file. But then I will depend on some apps which can filter data, a normal text editor is not so good in filtering data. I need to think about...

**Comment by aisbergde** [comment] 2020-05-25 19:12
with the new version I can open a file in any other folder - solved.

And now I can play a litte bit and give some more feedback:
- plain text is hard to read because of the word wrap, would be nice to have an option to toggle this on and off
- Regarding tags: If all is in one big file then a better filter system would be required, I like the filter options in "simpletask":
  - select multiple tags
  - exclude tags

And the good think is: I can open the same file in different apps or in a text editor. 

Maybe I really should try to use only 2 files (todo and done) and tags.

**Comment by xuhcc** [comment] 2020-05-25 21:11
>with the new version I can open a file in any other folder - solved.

OK, I'm closing this issue then.

>plain text is hard to read because of the word wrap, would be nice to have an option to toggle this on and off
> Regarding tags: If all is in one big file then a better filter system would be required, I like the filter options in "simpletask":
>         select multiple tags
>         exclude tags

Could you create new issues for these requests? Let's continue discussion there.

**Closed as completed by xuhcc** 2020-05-25 21:11 UTC

**Comment by ghost** [comment] 2021-02-17 03:08
> > /storage/emulated/0/Documents/markor/todo.txt is a valid file location
> > mindstream can't read this file
> 
> I succeeded in reproducing this problem, but with another location. It turned out that file picker couldn't determine the file path when the file is being selected from "SD card" location. I fixed this bug, improved error handling and published a new version: https://github.com/xuhcc/mindstream/releases/tag/v1.3.1.
> 
> Let me know if it would work for you.

I have this exact problem - trying to import the todo.txt file managed earlier by Markor at the quoted location.

At startup, after I tap the browse button and select todo.txt from the file picker, I get:

    Error: can not get file path

Mindstream v1.4.0 installed from Google Play Store
Android 10
MIUI 12.0.6
Mindstream has Storage permission
